import mouseinfo, pyautogui
1808,23
#mouseinfo.mouseInfo()
pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()

pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Undertaker and Kane")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("The Rock")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Hulk Hogan")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Kane wwe")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Vince Mcmahon")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Roman Reings")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("kiss")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Black Sabbath")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Iron Maiden")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Quenn")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Led Zepllin")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Metallica")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Guns n Roses")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("The Beatles")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Elvis Presley")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Bateria 2 bumbos")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Godzilla")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Guitarra")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Bateristas classicos")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Batman O Cavaleiro das Trevas")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Bruce Wayne")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Rock and Roll All Nite")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Renato Cariani")
pyautogui.press("Enter")

pyautogui.moveTo(498, 1053, duration=1)
pyautogui.click()
pyautogui.moveTo(1803, 33, duration=1)
pyautogui.click()
pyautogui.moveTo(1165, 1068, duration=1)
pyautogui.click()
pyautogui.moveTo(424, 70, duration=1)
pyautogui.click()

pyautogui.write("Rock n roll")
pyautogui.press("Enter")
