a=3
b=2
c=4
d=10
def operações():
    print(a+b)
    print(c*d)
    print(c+a*b)
    print(d+a-(c*b))
    print(c+a*(d/b))
    print(b-a/(c-d))
    print(a+d/(b-c))
    print(c+d/(a*b))
    print(a*d)
    print(d/c)
    print(d>a)
    print(a<d)
    print(a>c)
    print(a<b)
    print(c>a)
    print(c<b)
    print(b>d)
    print(a<c)
    print(c>d)
    print(c<d)
    print(a or b)
    print(d and d)
    print(a and c)
    print(c and b)
    print(b or a)
    print(c and a)
    print(b or c)
    print(not(a>b))
    print(not(c<a))
    print(not(a>c))
operações()